title: Database

columns:

  - width: 1/1
    sections:

      pagelist:
        type: pages
        headline: Subpages



  - width: 1/2
    sections:

      titleCol1:
        type: fields
        fields:
          title1:
            label: Items
            type: headline

      draftItems:
        headline: Drafts
        type: pages
        status: draft
        parent: site.find('database/items')
        templates: item

      unlistedItems:
        headline: In review
        type: pages
        status: unlisted
        parent: site.find('database/items')
        templates: item

      listedItems:
        headline: Published
        type: pages
        status: listed
        parent: site.find('database/items')
        templates: item

  - width: 1/2
    sections:

      titleCol2:
        type: fields
        fields:
          title2:
            label: People/Organizations
            type: headline

      draftEntities:
        headline: Drafts
        type: pages
        status: draft
        parent: site.find('database/entities')
        templates: entity

      unlistedEntities:
        headline: In review
        type: pages
        status: unlisted
        parent: site.find('database/entities')
        templates: entity

      listedEntities:
        headline: Published
        type: pages
        status: listed
        parent: site.find('database/entities')
        templates: entity
