title: Dashboard

tabs:

  otherPages:
    label: Pages
    sections:

      sitePages:
        type: pages
        headline: Site pages
        type: pages

  settings:
    label: Settings
    sections:

      menuSection:
        type: fields
        fields:

          siteDescription:
            label: Site description
            type: text
            help: Will be used for meta tags and social media

          menu:
            type: structure
            label: Menu
            fields:
              
              menuPage:
                label: Page
                type: pages
                min: 1
                max: 1
                width: 1/4
              
              subpages:
                label: Submenu
                type: pages
                width: 1/4

              visible:
                label: Visible
                type: toggle
                default: true
                text:
                  - "No"
                  - "Yes"
                width: 1/4

